### ISSUE TITLE
Any code?

### ISSUE THREAD

**Issue by itrack** [dolendravikas/directMessage#1]
Can you share some code? I'm very interested.

Thank you!

**Comment by vikas-atd** [comment]
Using the Stmduino framework, I have developed the GUI. The MCU I'm using in 'directMessage' uses an internal hardwired Sub-GHz SPI protocol to communicate with the RF stack that is embedded inside the MCU. These internal SPI pins can't be accessed using the regular SPI library provided by the stmduino. So yeah, for comms between two 'directMessages' I'm still working on it.

**Comment by dolendravikas** [comment]
Using the Stmduino framework, I have developed the GUI. The MCU I'm using in 'directMessage' uses an internal hardwired Sub-GHz SPI protocol to communicate with the RF stack embedded inside the MCU. These internal SPI pins can't be accessed using the regular SPI library provided by the stmduino. So yeah, for comms between two 'directMessages,' I'm still working on it.
